spring.application.name=franquicias
# Configuración de R2DBC PostgreSQL
# Configuración Dinámica de R2DBC PostgreSQL (compatible con Docker y ejecuciones locales)
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:franquicias_db}
spring.r2dbc.username=${DB_USER:postgres}
spring.r2dbc.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

# Logs de consultas R2DBC (reemplaza Hibernate SQL)
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG

spring.jackson.time-zone=America/Bogota
spring.webflux.base-path=/api/v1
server.port=8080
